[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "kiteconnect>=5.0.1",
    "openai==1.57.0",
    "pandas==2.2.3",
    "requests>=2.32.4",
    "streamlit>=1.47.1",
    "twilio==9.3.8",
]
